version: '2'

services:
  citas-ms:
    dns_search: .
    build: .     
    ports:
      - "4002:4002"    
    networks:
      - citas
  citas-db:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - "mongodata:/data/2g_citas_bd"
    networks:
      - citas
  
volumes:
   mongodata:

networks:
  citas:
